baseurl = "https://pikacloud.com/docs/"
languageCode = "en-us"
title = "Pikacloud documentation"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
canonifyurls = true

[params]
  editURL = "https://github.com/pikacloud/docs/edit/master/content/"
  description = "Pikacloud documentation"
  author = "Pikacloud"
